"""empty message

Revision ID: b3828494b7a7
Revises: 
Create Date: 2020-09-27 17:15:59.753958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3828494b7a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('secret_key', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.LargeBinary(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('displayed_name', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('oauth_provider_id', sa.Integer(), nullable=False),
    sa.Column('oauth_user_id', sa.String(length=128), nullable=False),
    sa.Column('oauth_token', sa.String(length=128), nullable=False),
    sa.Column('access_key', sa.String(length=128), nullable=False),
    sa.Column('key_expired', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['oauth_provider_id'], ['oauth_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activities',
    sa.Column('id', sa.LargeBinary(), nullable=False),
    sa.Column('creator_id', sa.LargeBinary(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('policy_number', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['activity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implementation_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insured_object_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.Column('attribute_3', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insured_person_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.Column('attribute_3', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_factory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.Column('attribute_3', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_forest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('is_person', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('primary_email', sa.String(length=64), nullable=True),
    sa.Column('secondary_email', sa.String(length=64), nullable=True),
    sa.Column('primary_phone', sa.String(length=16), nullable=True),
    sa.Column('secondary_phone', sa.String(length=16), nullable=True),
    sa.Column('risk_group', sa.String(length=64), nullable=True),
    sa.Column('current_occupation', sa.String(length=64), nullable=True),
    sa.Column('current_occupation_from', sa.Date(), nullable=True),
    sa.Column('previous_ocupation', sa.String(length=64), nullable=True),
    sa.Column('sports', sa.String(length=64), nullable=True),
    sa.Column('health_conditions', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.Column('attribute_3', sa.String(length=32), nullable=True),
    sa.Column('attribute_4', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_line_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_line_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.Column('attribute_3', sa.String(length=32), nullable=True),
    sa.Column('attribute_4', sa.String(length=32), nullable=True),
    sa.Column('attribute_5', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_line_life',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.Column('attribute_3', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_line_pnc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.LargeBinary(), nullable=False),
    sa.Column('attribute_1', sa.String(length=32), nullable=True),
    sa.Column('attribute_2', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_line_pnc')
    op.drop_table('product_line_life')
    op.drop_table('product_line_health')
    op.drop_table('product_line_car')
    op.drop_table('policy_attributes')
    op.drop_table('policies')
    op.drop_table('partners')
    op.drop_table('object_house')
    op.drop_table('object_forest')
    op.drop_table('object_field')
    op.drop_table('object_factory')
    op.drop_table('object_car')
    op.drop_table('insured_person_attributes')
    op.drop_table('insured_object_attributes')
    op.drop_table('implementation_attributes')
    op.drop_table('activities')
    op.drop_table('users')
    op.drop_table('oauth_providers')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
